dexonline/dexonline

templates/pageLayout.ihtml
Scop: modificarea campului de cautare (input), din "text" in "search", care creaza un buton de close/stergere a intregului continut, pentru usurarea cautarii urmatorului cuvant.
Modificari testate pe urmatoarele browsere: Chrome 40.0.2214.111, Firefox 13.0.1, Opera 12.11 & IE 9.
=> Introduce html5 atts in search form for mobile

wwwbase/styles/mobile.css
Tested on Chrome 40.0.2214.111, Firefox 13.0.1, Opera 12.11 & IE 9.0.8112.
Screenshots:
=> Optimize the search form for mobile

patches/00129.sql, patches/00130.php, phplib/FtpUtil.php, templates/bits/avatar.ihtml, wwwbase/salvare-avatar.php
* new function in `FtpUtil`: `staticServerRelativeFileList` that lists ftp
contents relative to the config path
* setting `hasAvatar` on avatar save and delete
* removing onerror from `avatar.ihtml`
* migration steps:
* 00129: add the new `hasAvatar` column to the `User` table
* 00130: get image list from FTP:`/img/user/` and set `hasAvatar = 1`
for matching user IDs
=> Adding hasAvatar user field (refs #341)

dex.conf.sample, phplib/SmartyWrap.php, phplib/models/Lexem.php, templates/bits/searchForm.ihtml, wwwbase/js/dex.js, wwwbase/searchComplete.php, wwwbase/searchcomplete.php
Changes
* `searchLike` method on `Lexem` 
* new `search` section in config
* `jqueryui` now loaded on all pages if `search.acEnable = true`
Results are cached in several places so it should not have that big of impact on performance:
* jquery autocomplete only does the request once the user stops typing
* previous requests are cached client side (until page refresh)
* `searchLike` uses memcahe
* Varnish should be able to cache the `searchcomplete.php` requests without issues
=> Autocomplete integration (#224)

templates/cuvinte-favorite.tpl, wwwbase/css/main.css
Favorite definitions need a spacing between them, easier to read and manage.
=> Add spacing for favorite definitions

dex.conf.sample, wwwbase/search.php
Also works for direct entries as the word is part of the URL and can be used to fetch a spoofed definition (line `187`).
The first `<b>` tag of the definition `htmlRep` is replaced by the word that was searched for. All custom markup is lost as a result. (`<sup>`, accents...).
Setting `spoofNormalize` to `false` will give more control over the definition, for each form of the word, but will also require defining a mapping for each form.
=> Definition spoofing support.

dex.conf.sample, templates/base.tpl, wwwbase/typewriter/run.js
No longer cookie guarded. If enabled, runs whenever `typewriter=1` is appended to the URL parameters.
Tested only on Firefox (GNU/Linux).
=> Separate config for typewriter.

phplib/AdminStringUtil.php
Convert the matched character (`$matches[1]`) instead of the entire match (`$matches[0]`, which includes the backslashes) to hex when exporting to XML. This should fix a bug where definition text such as `HOGAȘ, M\\. N\\.` gets dumped to XML as `HOGAȘ, M&#x5c; N&#x5c;`. `&#x5c;` is backslash, so the previous string translates to `HOGAȘ, M\ N\`.
=> Properly convert backslashed character

tools/updateLinks.php, wwwbase/editTree.php
Am continuat să lucrez la #632. Scriptul ar trebui să acopere cam toți itemii. În plus, generează și patch-uri SQL. M-am gândit că ar trebui și asta, ca să poată fi actualizată baza de date după ce o modifică scriptul.
=> Eliminare interactivă a trimiterilor redundante

wwwbase/admin/bulkReplace.php
Turns out that ¦ is not suitable for escaping. Duh!
=> Changed escaping sequence of reserved chars in bulkReplace.php

phplib/SmartyWrap.php, templates/admin/charmap.tpl, templates/layout-admin.tpl, wwwbase/js/charmap.js, wwwbase/js/hotkeys.js
This includes the changes from pull request https://github.com/dexonline/dexonline/pull/668, that one should be tested and merged first.
- Button popup for custom characters. 
- adding charmap.js to resources, loaded for editors
- keybinding set to `ctrl+alt+e`
Custom data is saved in a `charmap` cookie, valid for a century.
=> Character popup for editors.

wwwbase/js/charmap.js, wwwbase/js/tinymce.js
`keydown` events in the TinyMCE editor are now re-triggered on `$(document)`. This allows keybindings to work.
Adapted charmap to correctly handle tinymce as target.
=> [refs #671] charmap and keybindings in TinyMCE

phplib/Constant.php
Exclude \$ \@ \% from capturing when italic, bold and spaced segments are marked and not interfere with bulkReplace.
Constants for future use.
=> Exclude \$ \@ \% from capturing

wwwbase/css/main.css
The issue appears on most of the pages that have the .banner-section, eg: https://dexonline.ro/cuvantul-lunii/2018/07, https://dexonline.ro/articole
=> fix for horizontal overflow

phplib/Constant.php, phplib/htmlize/DeleteHtmlizer.php, phplib/htmlize/InsertHtmlizer.php, wwwbase/admin/bulkReplace.php
- eliminates the delay of diff.js when many occurrences have been found.
- correctly leaves #abbrev# fields untouched inside <del> and <ins> tags.
Above - old behavior ::: Below - new behavior:
=> Improved bulkReplace.

phplib/Constant.php, phplib/htmlize/DeleteHtmlizer.php, phplib/htmlize/InsertHtmlizer.php, wwwbase/istoria-definitiei.php
Definition history does not need diff.js anymore.
Create app-wide different SPACE constants.
Improved DeleteHtmlizer.
=> Make single-line regexp for del and ins htmlizers.

lib/models/PageIndex.php, patches/00298.php
Converting words in PageIndex table from IVO-III dictionary to non-diacritical character forms.
Adjustments to the PageIndex class in accordance to the above.
=> PageIndex-IVO-III

www/js/autoload/definition/edit.js
Fix when sourceDropdown is replaced with a disabled field as a result of source.canModerate = false.
=> getSimilarRecord-fix

www/css/main.css
accented vowels are not underlined when ligatures are set (default)
(affected \~f'i\~ sequences like geografie)
=> Inhibit ligatures.

lib/models/Entry.php, lib/models/Tree.php
Variants are displayed in the lexemeRank order, specified by the editor in the edit-entry form.
=> Ordered variants in frontend

www/ajax/searchComplete.php
For use in browser extensions and OpenSearch description documents.
See documentation here: https://github.com/dewitt/opensearch/blob/master/mediawiki/Specifications/OpenSearch/Extensions/Suggestions/1.1/Draft%201.wiki#JSONformatted_search_suggestion_responses
=> Add search suggestions in OpenSearch format

lib/Preferences.php
Înlocuire "minim" cu "minimum".
=> Înlocuire greșeală gramaticală
