templates/bits/searchForm.ihtml
wwwbase/styles/zepu.css

and combine search box with search button (looks like on mobiles).
screenshots here: https://github.com/CatalinFrancu/dexonline/issues/392

Refs #392: increase search box for desktop

---

wwwbase/styles/zepu.css

Refs #392: fix bug on Firefox: caută button displayed on another row

---

wwwbase/js/dex.js

După ani și ani am spus să particip și eu la acest proiect frumos :)
Acest pull-request este unul mic, ca de început.
El nu rezolvă o problemă mare, ci doar una infimă.

Animation cancel when slide is toggled again #489

---

patches/00182.sql

CREATE TABLE & INDEX of new abbreviation Table

[#420] creare tabela abrevieri

---

.gitignore
dex.conf.sample
phplib/util.php
templates/json/search.tpl
wwwbase/.htaccess.sample
wwwbase/search.php

Conform discuției de pe #562, am refactorat utilizarea lui $xml ca să accepte fie XML fie JSON.

Basic JSON format API response

---

phplib/Util.php

În pagina de moderare apare numărul sesizărilor, iar în pagina de vizualizare sesizări apare numărul intrărilor.

fixed skewed count of definition with typos

---

phplib/Core.php
phplib/FlashMessage.php
phplib/SmartyWrap.php
phplib/StringUtil.php
phplib/models/Visual.php
templates/admin/bulkReplace.tpl
templates/admin/index.tpl
templates/admin/pageUp.tpl
tools/checkVisualImages.php
tools/dumpDatabase.php
tools/old/generateLoadMonitorGraphs.php
tools/rebuildGameWordLists.php
tools/wotdImageReport.php
wwwbase/admin/bulkReplace.php
wwwbase/admin/editModel.php
wwwbase/css/autoload/pageUp.css
wwwbase/js/autoload/bulkReplace.js
wwwbase/js/autoload/pageUp.js
wwwbase/js/third-party/bootstrap-spinedit.js

Split in two columns the bulkReplace form dialog.
Added function for returning a valid temporary directory.
Changed some hard-coded paths.
Minor tweaks and repairs.
Added some comments.

Added pageUp template to be used, eventually, in large pages.

---

templates/bits/lexem.tpl

Hiding modelType and modelNumber for unprivileged users.

---

.editorconfig
phplib/SmartyWrap.php
wwwbase/auth/login.php

- Moving resources into array maps: This ensures ordering without needing to update array indexes when
adding new resources.
- Adding .editorconfig file: Editors that support this configuration, will automatically respect it. More info at http://editorconfig.org/
- Fixing test user login with no role selected.

Resource inclusion changes.

---

wwwbase/admin/abbrevInput.php

Error in processing htmlRep for abbreviations.

Str::htmlize now returns array.

---

phplib/Str.php
phplib/models/Definition.php
tools/test.php
wwwbase/css/autoload/search.css

La naiba cu formatările astea! Mie nu-mi arăta că aș fi distrus ceva.
Codul relevant este în `Definition::highlight`.
:(

Highlight every occurrence of searched words

---

lib/Constant.php

Prefix tweak.

---

templates/bits/loading.tpl
templates/bits/pageModal.tpl
www/ajax/getPage.php
www/css/main.css
www/js/admin.js

for subsequent searches after first time loading error

getPage-fix

---

templates/bits/definitionMenu.tpl
templates/bits/definitionTypoForm.tpl
templates/entry/edit.tpl
www/css/main.css
www/js/autoload/entry/edit.js

Ranges can be added by clicking or by continuous selection.

Send typos from edit-entry page.

---

www/js/autoload/definition/edit.js

by changing the way of clearing the values in entryIds selector

overcome a select2 issue

---

routes/lexeme/edit.php
templates/alerts/entryRenamed.tpl
templates/alerts/treeRenamed.tpl
www/css/third-party/ui.jqgrid.css

new names are linked instead of old ones

tweaking some alert messages after Entry and Tree renaming.

---

lib/models/Lexeme.php
routes/lexeme/edit.php
templates/bits/fragment.tpl
templates/bits/lexemeLink.tpl
templates/definition/edit.tpl
templates/lexeme/edit.tpl
www/css/main.css
www/js/autoload/lexeme/edit.js

- added link to fragments edit
- added possibility to jump back from fragment to lexeme
- restrict height of Select2 with too many items

Closes: #857

---

routes/lexeme/bulkLabel.php
routes/lexeme/edit.php
www/css/main.css

+array compoundIds was initialized only on first load.

Bulk label select suffix add tag

---

templates/bits/charmap.tpl
www/css/main.css
www/js/charmap.js
www/js/hotkeys.js

- Resolved bug when active keybinding could block the interface with
<div class="modal-backdrop fade in"></div> left undetached by modal close.
- Inserting more than one character without closing the modal.

Closes: #844

---

lib/Util.php
lib/models/Fragment.php
lib/models/InflectedForm.php
lib/models/Lexeme.php
lib/models/ObjectTag.php
routes/lexeme/edit.php
templates/bits/cloneEntryForm.tpl
templates/bits/cloneLexemeForm.tpl
templates/bits/cloneModal.tpl
templates/bits/definitionTypoForm.tpl
templates/entry/edit.tpl
templates/lexeme/edit.tpl
www/ajax/typo.php
www/js/autoload/definition/edit.js
www/js/autoload/entry/edit.js
www/js/autoload/lexeme/edit.js

- Lexeme can be cloned with multiple choices
- Refactored cloneModal to serve other purposes

Closes: #840

---

lib/Request.php
lib/Router.php
routes/wotd/view.php
templates/json/wotd.tpl
templates/xml/wotd.tpl

API functionality for
- word-of-the-day
- word-of-the-month 
serving json or xml

Resolves: #664

---

routes/wotm/view.php
templates/json/wotm.tpl
templates/wotm/view.tpl
templates/xml/wotm.tpl

Wotm JSON/XML support

---

www/js/dex.js

Fixed last entry in list unclickable bug
